import doctor1 from "../Doctors/doctor1.png";
import doctor2 from "../Doctors/doctor2.png";
import doctor3 from "../Doctors/doctor3.png";
import doctor4 from "../Doctors/doctor4.png";
import doctor5 from "../Doctors/doctor5.png";
import doctor6 from "../Doctors/doctor6.png";
import doctor7 from "../Doctors/doctor7.png";
import doctor8 from "../Doctors/doctor8.png";

const reasons = [
  "Lunch Break",
  "Meeting",
  "Conference",
  "Personal",
  "Reserved",
  "Important",
];
export const Doctors = {
  Doctor1: {
    fullname: "Dr. John Smith",
    occupation: "Cardiologist",
    description: "Expert in heart-related illnesses and treatments.",
    img: doctor5,
    id: 1,
    schedule: {
      Monday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[1] },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[4] },
        { time: "4 PM", reason: "" },
      ],
      Tuesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[4] },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: reasons[4] },
      ],
      Wednesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: reasons[2] },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Thursday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[4] },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: reasons[4] },
        { time: "3 PM", reason: reasons[1] },
        { time: "4 PM", reason: "" },
      ],
      Friday: [
        { time: "10 AM", reason: reasons[5] },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: reasons[2] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[4] },
        { time: "4 PM", reason: reasons[3] },
      ],
    },
  },
  Doctor2: {
    fullname: "Dr. Emily Johnson",
    occupation: "Pediatrician",
    description: "Specialist in chidren's health and wellness.",
    img: doctor1,
  },
  Doctor3: {
    fullname: "Dr. Michael Brown",
    occupation: "Dermatologist",
    description: "Focused on skin conditions and cosmetic procedures.",
    img: doctor2,
    id: 2,
  },
  Doctor4: {
    fullname: "Dr. Sarah Davis",
    occupation: "Neurologist",
    description: "Deals with brain and nervous system disorders.",
    img: doctor4,
    id: 3,
  },
  Doctor5: {
    fullname: "Dr. William Wilson",
    occupation: "Orthopedic Surgeon",
    description: "Specializes in bones, joints, and musculoskeletal issues.",
    img: doctor3,
    id: 4,
  },
  Doctor6: {
    fullname: "Dr. Olivia Martinez",
    occupation: "Ophthalmologist",
    description: "Expert in eye care and vision correction.",
    img: doctor7,
    id: 5,
  },
  Doctor7: {
    fullname: "Dr. James Anderson",
    occupation: "General Practitioner",
    description: "Focuses on mental health and psychological disorders.",
    img: doctor6,
    id: 6,
    schedule: {
      Monday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[1] },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[4] },
        { time: "4 PM", reason: "" },
      ],
      Tuesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[4] },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: reasons[4] },
      ],
      Wednesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: reasons[2] },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Thursday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[4] },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: reasons[4] },
        { time: "3 PM", reason: reasons[1] },
        { time: "4 PM", reason: "" },
      ],
      Friday: [
        { time: "10 AM", reason: reasons[5] },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: reasons[2] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[4] },
        { time: "4 PM", reason: reasons[3] },
      ],
    },
  },
  Doctor8: {
    fullname: "Dr. Sophia Thomas",
    occupation: "General Practitioner",
    description: "Provides overall medical care for all ages.",
    img: doctor8,
    id: 7,
    schedule: {
      Monday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: reasons[1] },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: reasons[4] },
      ],
      Tuesday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: reasons[4] },
        { time: "7 PM", reason: "" },
        { time: "8 PM", reason: reasons[0] },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Wednesday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: reasons[2] },
        { time: "10 PM", reason: "" },
      ],
      Thursday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: " " },
        { time: "7 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Friday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: "" },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Saturday: [
        { time: "10 AM", reason: reasons[5] },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: reasons[2] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[4] },
        { time: "4 PM", reason: reasons[3] },
      ],
    },
  },
};
