import mongoose from "mongoose";
import dotenv from "dotenv";

import { Doctor } from "./Schemas.js";

dotenv.config();

const reasons = [
  "Lunch Break",
  "Meeting",
  "Conference",
  "Personal",
  "Reserved",
  "Important",
];
export const Doctors = {
  Doctor1: {
    fullname: "Dr. John Smith",
    occupation: "Cardiologist",
    description: "Expert in heart-related illnesses and treatments.",
    img: "/Doctorspic/doctor5.png",
    schedule: {
      Monday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Tuesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Wednesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Thursday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Friday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
    },
  },
  Doctor2: {
    fullname: "Dr. Emily Johnson",
    occupation: "Dermatologist",
    description: "Specialist in skin conditions and cosmetic treatments.",
    img: "/Doctorspic/doctor2.png",
    schedule: {
      Monday: [
        { time: "8 AM", reason: "" },
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[0] },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
      ],
      Tuesday: [
        { time: "8 AM", reason: "" },
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
      ],
      Wednesday: [
        { time: "8 AM", reason: "" },
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
      ],
      Thursday: [
        { time: "8 AM", reason: "" },
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: reasons[0] },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
      ],
      Friday: [
        { time: "8 AM", reason: "" },
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[0] },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
      ],
    },
  },

  Doctor3: {
    fullname: "Dr. Michael Brown",
    occupation: "Surgeon",
    description: "Performs surgical operations with high precision and care.",
    img: "/Doctorspic/doctor3.png",
    schedule: {
      Monday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Tuesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: reasons[0] },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Wednesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Thursday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[0] },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Friday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[0] },
        { time: "4 PM", reason: "" },
      ],
    },
  },

  Doctor4: {
    fullname: "Dr. Sarah Williams",
    occupation: "Neurologist",
    description: "Expert in treating brain, spinal cord, and nerve disorders.",
    img: "/Doctorspic/doctor4.png",
    schedule: {
      Monday: [
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: reasons[0] },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
      ],
      Tuesday: [
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: reasons[0] },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
      ],
      Wednesday: [
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
      ],
      Thursday: [
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: reasons[0] },
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
      ],
      Friday: [
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: reasons[0] },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
      ],
      Saturday: [
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: reasons[0] },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
      ],
    },
  },

  Doctor5: {
    fullname: "Dr. David Lee",
    occupation: "Orthopedic Specialist",
    description: "Treats bone, joint, and muscle conditions effectively.",
    img: "/Doctorspic/doctor5.png",
    schedule: {
      Monday: [
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
      ],
      Tuesday: [
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: reasons[0] },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
      ],
      Wednesday: [
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
      ],
      Thursday: [
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
      ],
      Friday: [
        { time: "9 AM", reason: "" },
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
      ],
    },
  },

  Doctor6: {
    fullname: "Dr. Olivia Davis",
    occupation: "Surgeon",
    description:
      "Experienced surgeon with expertise in general and emergency operations.",
    img: "/Doctorspic/doctor6.png",
    schedule: {
      Monday: [
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Tuesday: [
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Wednesday: [
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
        { time: "7 PM", reason: "" },
        { time: "8 PM", reason: reasons[0] },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Thursday: [
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: reasons[0] },
        { time: "7 PM", reason: "" },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Friday: [
        { time: "4 PM", reason: "" },
        { time: "5 PM", reason: "" },
        { time: "6 PM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
    },
  },
  Doctor7: {
    fullname: "Dr. James Anderson",
    occupation: "General Practitioner",
    description: "Focuses on mental health and psychological disorders.",
    img: "/Doctorspic/doctor7.png",
    schedule: {
      Monday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Tuesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: "" },
        { time: "1 PM", reason: reasons[0] },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Wednesday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Thursday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
      Friday: [
        { time: "10 AM", reason: "" },
        { time: "11 AM", reason: "" },
        { time: "12 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "2 PM", reason: "" },
        { time: "3 PM", reason: "" },
        { time: "4 PM", reason: "" },
      ],
    },
  },
  Doctor8: {
    fullname: "Dr. Sophia Thomas",
    occupation: "General Practitioner",
    description: "Provides overall medical care for all ages.",
    img: "/Doctorspic/doctor8.png",
    schedule: {
      Monday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Tuesday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: "" },
        { time: "8 PM", reason: reasons[0] },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Wednesday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "8 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Thursday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: reasons[0] },
        { time: "1 PM", reason: "" },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
      Friday: [
        { time: "5 AM", reason: "" },
        { time: "6 AM", reason: "" },
        { time: "7 PM", reason: "" },
        { time: "8 PM", reason: reasons[0] },
        { time: "9 PM", reason: "" },
        { time: "10 PM", reason: "" },
      ],
    },
  },
};

mongoose
  .connect(process.env.MONGODB)
  .then(async () => {
    await Doctor.deleteMany();
    await Doctor.insertMany(Object.values(Doctors));
    console.log("Doctors inserted");
    process.exit();
  })
  .catch((err) => console.log(err));
